# Quasar Demo

In [1]:
import quasar

## Layer 1: The Quasar Circuit Class

### Example 1: A GHZ Circuit

In [2]:
circuit = quasar.Circuit(N=3).H(0).CX(0,1).CX(1,2)
print(circuit)
print(circuit.param_str)

T  : |0|1|2|
            
q0 : -H-@---
        |   
q1 : ---X-@-
          | 
q2 : -----X-

T  : |0|1|2|
Index Time  Qubits     Name       Gate      :     Value



In [3]:
for key, gate in circuit.gates.items():
    time, qubits = key
    print('%2d %7s: %s' % (time, qubits, gate))

 0    (0,): H
 1  (0, 1): CX
 2  (1, 2): CX


In [4]:
print(circuit.N)
print(circuit.ngate)
print(circuit.ngate1)
print(circuit.ngate2)
print(circuit.ntime)

3
3
1
2
3


### Example 2: A CIS Circuit

In [5]:
gadget = quasar.Circuit(N=2).Ry(1).CZ(0,1).Ry(1).CX(1,0)
print(gadget)

T  : |0 |1|2 |3|
                
q0 : ----@----X-
         |    | 
q1 : -Ry-Z-Ry-@-

T  : |0 |1|2 |3|


In [6]:
circuit = quasar.Circuit(N=4)
circuit.Ry(0, theta=0.2)
circuit.add_circuit(gadget, (0,1))
circuit.add_circuit(gadget, (1,2))
circuit.add_circuit(gadget, (2,3))
print(circuit)

T  : |0 |1|2 |3 |4|5 |6 |7|8 |9|
                                
q0 : -Ry-@----X-----------------
         |    |                 
q1 : -Ry-Z-Ry-@--@----X---------
                 |    |         
q2 : ---------Ry-Z-Ry-@--@----X-
                         |    | 
q3 : -----------------Ry-Z-Ry-@-

T  : |0 |1|2 |3 |4|5 |6 |7|8 |9|


In [7]:
print(circuit.param_str)

Index Time  Qubits     Name       Gate      :     Value
0     0     (0,)       theta      Ry        :  0.200000
1     0     (1,)       theta      Ry        :  0.000000
2     2     (1,)       theta      Ry        :  0.000000
3     3     (2,)       theta      Ry        :  0.000000
4     5     (2,)       theta      Ry        :  0.000000
5     6     (3,)       theta      Ry        :  0.000000
6     8     (3,)       theta      Ry        :  0.000000



In [8]:
circuit.set_param_values([0.9, -0.1, +0.1, +0.2, -0.2, +0.3, -0.3])
print(circuit.param_str)

Index Time  Qubits     Name       Gate      :     Value
0     0     (0,)       theta      Ry        :  0.900000
1     0     (1,)       theta      Ry        : -0.100000
2     2     (1,)       theta      Ry        :  0.100000
3     3     (2,)       theta      Ry        :  0.200000
4     5     (2,)       theta      Ry        : -0.200000
5     6     (3,)       theta      Ry        :  0.300000
6     8     (3,)       theta      Ry        : -0.300000



In [9]:
print(circuit.param_keys)

[(0, (0,), 'theta'), (0, (1,), 'theta'), (2, (1,), 'theta'), (3, (2,), 'theta'), (5, (2,), 'theta'), (6, (3,), 'theta'), (8, (3,), 'theta')]


In [10]:
print(circuit.simulate().real.round(3))

[ 0.622  0.034 -0.05   0.     0.143  0.     0.     0.     0.768  0.
 -0.     0.     0.    -0.     0.    -0.   ]


In [11]:
measurement = circuit.measure(nmeasurement=1000)
print(measurement)
# measurement2 = measurement.mask_qubits([0,1]) # TODO
print(measurement['0000'])

|0000> : 383
|0001> :   1
|0010> :   2
|0100> :  18
|1000> : 596

383


In [12]:
for key, ncount in measurement.items():
    print(key, ncount)

0000 383
0001 1
0010 2
0100 18
1000 596


In [13]:
print(key[0])
print(key[1])

1
0


## Layer 2: Backends, Statevectors, Measurements, and Paulis

In [14]:
backend = quasar.QuasarSimulatorBackend()
print(backend)
print(backend.summary_str)
print(backend.has_statevector)
print(backend.has_measurement)
print(backend.native_circuit_type)

Quasar Simulator Backend (Statevector)
Quasar: An Ultralite Quantum Circuit Simulator
   By Rob Parrish (rob.parrish@qcware.com)    
True
True
<class 'quasar.circuit.Circuit'>


In [15]:
backend = quasar.QiskitSimulatorBackend()
print(backend)
print(backend.summary_str)
print(backend.has_statevector)
print(backend.has_measurement)
print(backend.native_circuit_type)

Qiskit Simulator Backend
Qiskit Simulator Backend
True
True
<class 'qiskit.circuit.quantumcircuit.QuantumCircuit'>


/anaconda3/lib/python3.7/site-packages/marshmallow/schema.py:364: ChangedInMarshmallow3Warning: strict=False is not recommended. In marshmallow 3.0, schemas will always be strict. See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict
  ChangedInMarshmallow3Warning


In [16]:
backend = quasar.CirqSimulatorBackend()
print(backend)
print(backend.summary_str)
print(backend.has_statevector)
print(backend.has_measurement)
print(backend.native_circuit_type)

Cirq Simulator Backend
Cirq Simulator Backend
True
True
<class 'cirq.circuits.circuit.Circuit'>


In [17]:
backends = [
    quasar.QuasarSimulatorBackend(),
    quasar.QiskitSimulatorBackend(),
    quasar.CirqSimulatorBackend(),
]

In [18]:
circuit = quasar.Circuit(N=3).H(0).CX(0,1).CX(1,2)
print(circuit)

T  : |0|1|2|
            
q0 : -H-@---
        |   
q1 : ---X-@-
          | 
q2 : -----X-

T  : |0|1|2|


In [19]:
circuits = [quasar.build_native_circuit(backend, circuit) for backend in backends]
for circuit in circuits:
    print(circuit)

T  : |0|1|2|
            
q0 : -H-@---
        |   
q1 : ---X-@-
          | 
q2 : -----X-

T  : |0|1|2|
         ┌───┐          
q0_0: |0>┤ H ├──■───────
         └───┘┌─┴─┐     
q0_1: |0>─────┤ X ├──■──
              └───┘┌─┴─┐
q0_2: |0>──────────┤ X ├
                   └───┘
0: ───H───@───────
          │
1: ───────X───@───
              │
2: ───────────X───


In [20]:
for backend in backends:
    for circuit in circuits:
        print(quasar.build_native_circuit(backend, circuit))

T  : |0|1|2|
            
q0 : -H-@---
        |   
q1 : ---X-@-
          | 
q2 : -----X-

T  : |0|1|2|
T  : |0|1|2|
            
q0 : -H-@---
        |   
q1 : ---X-@-
          | 
q2 : -----X-

T  : |0|1|2|
T  : |0|1|2|
            
q0 : -H-@---
        |   
q1 : ---X-@-
          | 
q2 : -----X-

T  : |0|1|2|
         ┌───┐          
q1_0: |0>┤ H ├──■───────
         └───┘┌─┴─┐     
q1_1: |0>─────┤ X ├──■──
              └───┘┌─┴─┐
q1_2: |0>──────────┤ X ├
                   └───┘
         ┌───┐          
q0_0: |0>┤ H ├──■───────
         └───┘┌─┴─┐     
q0_1: |0>─────┤ X ├──■──
              └───┘┌─┴─┐
q0_2: |0>──────────┤ X ├
                   └───┘
         ┌───┐          
q2_0: |0>┤ H ├──■───────
         └───┘┌─┴─┐     
q2_1: |0>─────┤ X ├──■──
              └───┘┌─┴─┐
q2_2: |0>──────────┤ X ├
                   └───┘
0: ───H───@───────
          │
1: ───────X───@───
              │
2: ───────────X───
0: ───H───@───────
          │
1: ───────X───@───
              │
2: ──────

In [21]:
import numpy as np
for backend in backends:
    for circuit in circuits:
        print(np.abs(quasar.run_statevector(backend, circuit)**2))

[0.5 0.  0.  0.  0.  0.  0.  0.5]
[0.5 0.  0.  0.  0.  0.  0.  0.5]
[0.5 0.  0.  0.  0.  0.  0.  0.5]
[0.5 0.  0.  0.  0.  0.  0.  0.5]
[0.5 0.  0.  0.  0.  0.  0.  0.5]
[0.5 0.  0.  0.  0.  0.  0.  0.5]
[0.49999998 0.         0.         0.         0.         0.
 0.         0.49999998]
[0.49999998 0.         0.         0.         0.         0.
 0.         0.49999998]
[0.49999998 0.         0.         0.         0.         0.
 0.         0.49999998]


/anaconda3/lib/python3.7/site-packages/marshmallow/schema.py:364: ChangedInMarshmallow3Warning: strict=False is not recommended. In marshmallow 3.0, schemas will always be strict. See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict
  ChangedInMarshmallow3Warning


In [22]:
for backend in backends:
    for circuit in circuits:
        print(quasar.run_measurement(backend, circuit, nmeasurement=1000))

|000> : 505
|111> : 495

|000> : 515
|111> : 485

|000> : 508
|111> : 492

|000> : 498
|111> : 502

|000> : 556
|111> : 444

|000> : 514
|111> : 486

|000> : 493
|111> : 507

|000> : 472
|111> : 528

|000> : 486
|111> : 514



In [23]:
I, X, Y, Z = quasar.Pauli.IXYZ()

In [24]:
print(quasar.Matrix.Y)

[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]


In [25]:
pauli = I + Z[0] + Z[1] + Z[2]
pauli += Z[0] * Z[1] + Z[1] * Z[2]
pauli += Z[0] * Z[1] * Z[2]
pauli += X[0]
print(pauli)

+1.0*I
+1.0*Z0
+1.0*Z1
+1.0*Z2
+1.0*Z0*Z1
+1.0*Z1*Z2
+1.0*Z0*Z1*Z2
+1.0*X0


In [26]:
for backend in backends:
    for circuit in circuits:
        print(quasar.run_pauli_expectation(backend, circuit, pauli, nmeasurement=1000))
        print('')

<I> = 1.0
<Z0> = -0.014
<Z1> = -0.036
<Z2> = -0.014
<Z0*Z1> = 1.0
<Z1*Z2> = 1.0
<Z0*Z1*Z2> = -0.07
<X0> = 0.02

<I> = 1.0
<Z0> = -0.001
<Z1> = -0.05
<Z2> = -0.001
<Z0*Z1> = 1.0
<Z1*Z2> = 1.0
<Z0*Z1*Z2> = -0.032
<X0> = 0.022

<I> = 1.0
<Z0> = 0.015
<Z1> = -0.004
<Z2> = 0.015
<Z0*Z1> = 1.0
<Z1*Z2> = 1.0
<Z0*Z1*Z2> = 0.012
<X0> = 0.046

<I> = 1.0
<Z0> = 0.017
<Z1> = 0.006
<Z2> = 0.017
<Z0*Z1> = 1.0
<Z1*Z2> = 1.0
<Z0*Z1*Z2> = 0.018
<X0> = -0.005

<I> = 1.0
<Z0> = -0.02
<Z1> = -0.051
<Z2> = -0.02
<Z0*Z1> = 1.0
<Z1*Z2> = 1.0
<Z0*Z1*Z2> = -0.044
<X0> = 0.012

<I> = 1.0
<Z0> = -0.001
<Z1> = 0.008
<Z2> = -0.001
<Z0*Z1> = 1.0
<Z1*Z2> = 1.0
<Z0*Z1*Z2> = -0.02
<X0> = -0.009

<I> = 1.0
<Z0> = 0.008
<Z1> = -0.014
<Z2> = 0.008
<Z0*Z1> = 1.0
<Z1*Z2> = 1.0
<Z0*Z1*Z2> = 0.01
<X0> = -0.004

<I> = 1.0
<Z0> = 0.034
<Z1> = 0.001
<Z2> = 0.034
<Z0*Z1> = 1.0
<Z1*Z2> = 1.0
<Z0*Z1*Z2> = 0.008
<X0> = 0.0

<I> = 1.0
<Z0> = 0.035
<Z1> = -0.003
<Z2> = 0.035
<Z0*Z1> = 1.0
<Z1*Z2> = 1.0
<Z0*Z1*Z2> = 0.022
<X0> = -0.01

## Layer 3: Gradients, Hessians, and Tomography

In [27]:
run_observable_expectation_value(backend, circuit, pauli)

NameError: name 'run_observable_expectation_value' is not defined