In [37]:
import quasar
import mcvqe

In [38]:
filenames = ['../data/aiem/bchl-a-8-stack/tc/%s/exciton.dat' 
             % (A) for A in range(1,8+1)]
aiem_monomer = mcvqe.AIEMMonomer.from_tc_exciton_files(
    filenames=filenames,
    N=2,
    connectivity='linear',
    )

In [39]:
backend = quasar.QuasarSimulatorBackend()

In [41]:
mcvqe_solver = mcvqe.MCVQE.from_options(
    backend=backend,
    aiem_monomer=aiem_monomer,
    nstate=2,
    )
mcvqe_solver.compute_energy()

==> MC-VQE+AIEM <==

Quantum Resources:
  Backend        = Quasar Simulator Backend (Statevector)
  Shots          = None
  Shots Subspace = None
  Shots Deriv    = None

AIEM Problem:
 N            = 2
 Ncis         = 3
 Nstate       = 2
 Connectivity = linear

CIS Verification:

State:       Match
0    :  -2.776E-17
1    :   1.214E-17

SA-VQE Weights:

State:      Weight
0    :   5.000E-01
1    :   5.000E-01

VQE Entangler Circuit:
  vqe_circuit_type = mark1x
  vqe_nparam       = 6

Initital VQE params guessed as zero.

 > BFGS Optimizer <

  maxiter       = 100
  g_convergence = 1.000E-06

 > End BFGS Optimizer <

Finished VQE Circuit:

T  : |0 |1|2 |3|4 |
                   
q0 : -Ry-@-Ry-@-Ry-
         |    |    
q1 : -Ry-X-Ry-X-Ry-

T  : |0 |1|2 |3|4 |

Finished VQE Parameters:

Index Time  Qubits     Name       Gate      :     Value
0     0     (0,)       theta      Ry        :  0.068010
1     0     (1,)       theta      Ry        :  0.045097
2     2     (0,)       theta      Ry

In [5]:
print(mcvqe.hamiltonian_pauli)

+0.013958292661992958*X0
-0.03376113630025557*Z0
+0.010972023904919113*X1
-0.04283574018078509*Z1
+0.017780394781136848*X0*X1
-0.006896704529177866*X0*Z1
+0.011474775121306156*Z0*X1
-0.004444563032874407*Z0*Z1


In [42]:
H = mcvqe_solver.hamiltonian_pauli.compute_hilbert_matrix(dtype=float)
print(H)

[[-0.08104144  0.0224468   0.00706159  0.01778039]
 [ 0.0224468   0.01351917  0.01778039  0.020855  ]
 [ 0.00706159  0.01778039 -0.00463004 -0.00050275]
 [ 0.01778039  0.020855   -0.00050275  0.07215231]]


In [44]:
import numpy as np
E = np.linalg.eigh(H)[0]
for I in range(mcvqe_solver.nstate):
    print('%11.3E' % (E[I] - mcvqe_solver.fci_E[I]))

  0.000E+00
  0.000E+00


In [46]:
I = 3
statevector = np.zeros((2**mcvqe_solver.N,))
statevector[I] = 1.0
Hrow = mcvqe_solver.hamiltonian_pauli.compute_hilbert_matrix_vector_product(statevector)

print(Hrow)
print(H[I,:])

[ 0.01778039  0.020855   -0.00050275  0.07215231]
[ 0.01778039  0.020855   -0.00050275  0.07215231]
